# Конфігурація ShopTrader

# Ціни за рідкістю (використовуються для ротаційних предметів у магазині)
prices:
  common: 500.0
  uncommon: 1000.0
  epic: 3000.0
  legendary: 5000.0
  # Ціна, що застосовується до предметів категорії GARBAGE (різне, нефункціональне).
  garbage: 2.0


rotation:
  minutes: 30
  cycle_seconds: 30
  counts:
    common: 4
    uncommon: 3
    epic: 3
    legendary: 1

# Оцінка зачарувань для спорядження (застосовується до зброї/інструментів/бронь у ротаційному магазині)
enchant:
  price_multiplier: 1.5
  # Налаштування випадкових зачарувань (для ротаційних предметів магазину)
  # Множник = 1.0 + coefficient * quality, обмежений shop.enchant.max_multiplier
shop:
  enchant:
    random:
      coefficient: 0.25
    max_multiplier: 3.0

# Предмети, що випадають у кількох одиницях з одного блоку, мають бути дешевші за одиницю.
# Налаштуйте коефіцієнти для матеріалів (1.0 = без змін, 0.25 = на 75% дешевше за одиницю).
pricing:
  yield:
    by_material:
      REDSTONE: 0.25
      LAPIS_LAZULI: 0.25
      GLOWSTONE_DUST: 0.25
      AMETHYST_SHARD: 0.25
      NETHER_QUARTZ: 0.8
      PRISMARINE_CRYSTALS: 0.6
      PRISMARINE_SHARD: 0.6
  dynamic:
    # Після кожних N покупок матеріалу множник ціни в магазині підвищується на shop_increase_factor
    shop_increase_every_n_buys: 3
    shop_increase_factor: 0.10
    max_shop_multiplier: 3.0
    # Коли гравці продають предмети, зменшуйте коефіцієнти продажу й магазину для відображення надлишку
    sell_decrease_per_item: 0.005
    min_sell_multiplier: 0.25
    shop_decrease_per_item_on_sell: 0.02
    min_shop_multiplier: 0.8

# Налаштування продажу
sell:
  # Базовий множник ціни продажу відносно поточної ціни покупки (ціни магазину). 0.45 = 45% від покупки
  base_multiplier: 0.05
  # Якщо true, предмети категорії GARBAGE не можна продавати
  block_garbage_category: true
  # Додатковий чорний список матеріалів для продажу (назви мають відповідати Bukkit Material)
  blacklist:
    - ROTTEN_FLESH
    - POISONOUS_POTATO
    - SPIDER_EYE
    - DEAD_BUSH

# Спеціальні категорії
spawn_egg:
  price: 2500.0
lucky_block:
  price: 500.0
  prices:
    common: 500.0
    rare: 1500.0
    epic: 3000.0

trader:
  world: world
  x: -102.69999998807907
  y: 66.0
  z: 232.00014374219506
  yaw: 88.34999
  pitch: 12.974391
  uuid: 5d32f4d6-5e0a-4776-822f-85c88bda7667
